'use strict';

angular.module('reportsModule').constant('RVReportNamesConst', {
    'CHECK_IN_CHECK_OUT': 'Check In / Check Out',
    'CHECKIN_NOW_OR_LATER': 'Check In - Now or Later',
    'UPSELL': 'Upsell',
    'ROOM_UPSELL': 'Room Upsell',
    'WEB_CHECK_OUT_CONVERSION': 'Web Check Out Conversion',
    'WEB_CHECK_IN_CONVERSION': 'Web Check In Conversion',
    'WEB_CHECK_IN_CONV_BY_DAY': 'Web Check In Conversion By Day',
    'LATE_CHECK_OUT': 'Late Check Out',
    'EARLY_CHECKIN': 'Early Check In',
    'IN_HOUSE_GUEST': 'In-House Guests',
    'ARRIVAL': 'Arrival',
    'DEPARTURE': 'Departure',
    'BOOKING_SOURCE_MARKET_REPORT': 'Booking Source & Market Report',
    'CANCELLATION_NO_SHOW': 'Cancellation & No Show',
    'DEPOSIT_REPORT': 'Guest Deposit Report',
    'GROUP_DEPOSIT_REPORT': 'Group Deposit Report',
    'LOGIN_AND_OUT_ACTIVITY': 'Login and out Activity',
    'OCCUPANCY_REVENUE_SUMMARY': 'Occupancy & Revenue Summary',
    'RESERVATIONS_BY_USER': 'Reservations By User',
    'DAILY_TRANSACTIONS': 'Daily Transactions',
    'DAILY_PAYMENTS': 'Daily Payments',
    'FORECAST_BY_DATE': 'Forecast',
    'ROOMS_QUEUED': 'Rooms Queued',
    'FORECAST_GUEST_GROUPS': 'Forecast Guests & Groups',
    'MARKET_SEGMENT_STAT_REPORT': 'Market Segment Statistics Report',
    'MOBILE_CHECKIN_NOW': 'Mobile Check In - Now',
    'MOBILE_CHECKIN': 'Mobile Check In',
    'COMPARISION_BY_DATE': 'Comparison',
    'RATE_ADJUSTMENTS_REPORT': 'Rate Adjustment Report',
    'GROUP_PICKUP_REPORT': 'Group Pick Up Report',
    'GUEST_BALANCE_REPORT': 'Guest Balance Report',
    'ADDON_FORECAST': 'Add-On Forecast',
    'ALLOWANCE_FORECAST': 'Allowance Forecast Report',
    'DAILY_PRODUCTION_ROOM_TYPE': 'Daily Production',
    'AR_SUMMARY_REPORT': 'A/R Summary Report',
    'DAILY_PRODUCTION_DEMO': 'Daily Production by Demographics',
    'DAILY_PRODUCTION_RATE': 'Daily Production by Rate',
    'RATE_RESTRICTION_REPORT': 'Rate & Restrictions',
    'COMPANY_TA_TOP_PRODUCERS': 'Company/TA Top Producers',
    'FINANCIAL_TRANSACTIONS_ADJUSTMENT_REPORT': 'Financial Transactions - Adjustment Report',
    'CREDIT_CHECK_REPORT': 'Credit Check Report',
    'DEPOSIT_SUMMARY': 'Deposit Balance Summary',
    'ZEST_CAMPAIGN_REPORT': 'Zest App Campaign Report',
    'ROOMS_OOO_OOS': 'Rooms OOO/OOS',
    'ACTIONS_MANAGER': 'Action Manager',
    'VACANT_ROOMS_REPORT': 'Vacant Rooms Report',
    'A/R_AGING': 'A/R Aging',
    'TRAVEL_AGENT_COMMISSIONS': 'Travel Agent Commissions',
    'BUSINESS_ON_BOOKS': 'Business on the Books',
    'COMPLIMENTARY_ROOM_REPORT': 'Complimentary Room Report',
    'GROUP_ROOMS_REPORT': 'Group Rooms Report',
    'ADDON_UPSELLS': 'Add On Upsell',
    'YEARLY_TAX': 'Yearly Tax Report',
    'TAX_EXEMPT': 'Tax Exempt',
    'FOLIO_TAX_REPORT': 'Folio Tax Report',
    'GUESTS_INHOUSE_BY_NATIONALITY': 'Guests In House by Nationality',
    'BUSINESS_ON_THE_BOOKS': 'Business on the Books',
    'ROOM_STATUS_REPORT': 'Room Status Report',
    'FINANCIAL_TRANSACTION_REVENUE_REPORT': 'Financial Transaction - Revenue Report',
    'FINANCIAL_TRANSACTION_PAYMENT_REPORT': 'Financial Transaction - Payment Report',
    'FINANCIAL_TRANSACTION_SUMMARY_REPORT': 'Financial Transaction - Summary Report',
    'TAX_OUTPUT_REPORT': 'Tax Output Report - Tax Payment Receipts'
});