'use strict';

angular.module('reportsModule').constant('RVReportPaginationIdsConst', {
    'Action Manager': 'ACTIONS_MANAGER',
    'Arrival': 'ARRIVAL',
    'Cancellation & No Show': 'CANCELLATION_NO_SHOW',
    'Departure': 'DEPARTURE',
    'Guest Balance Report': 'GUEST_BALANCE_REPORT',
    'Guest Deposit Report': 'DEPOSIT_REPORT',
    'In-House Guests': 'IN_HOUSE_GUEST',
    'Late Check Out': 'LATE_CHECK_OUT',
    'Login and out Activity': 'LOGIN_AND_OUT_ACTIVITY',
    'Rate Adjustment Report': 'RATE_ADJUSTMENTS_REPORT',
    'Vacant Rooms Report': 'VACANT_ROOMS_REPORT',
    'A/R Summary Report': 'AR_SUMMARY_REPORT',
    'Forecast': 'FORECAST_BY_DATE',
    'Forecast Guests & Groups': 'FORECAST_GUEST_GROUPS',
    'Reservations By User': 'RESERVATIONS_BY_USER',
    'Upsell': 'UPSELL',
    'Room Upsell': 'ROOM_UPSELL',
    'Rooms OOO/OOS': 'ROOMS_OOO_OOS',
    'Company/TA Top Producers': 'COMPANY_TA_TOP_PRODUCERS',
    'Credit Check Report': 'CREDIT_CHECK_REPORT',
    'Deposit Balance Summary': 'DEPOSIT_SUMMARY',
    'Business on the Books': 'BUSINESS_ON_BOOKS',
    'Complimentary Room Report': 'COMPLIMENTARY_ROOM_REPORT',
    'Group Rooms Report': 'GROUP_ROOMS_REPORT',
    'Add On Upsell': 'ADDON_UPSELLS',
    'Tax Exempt': 'TAX_EXEMPT',
    'Folio Tax Report': 'FOLIO_TAX_REPORT',
    'Guests In House by Nationality': 'GUESTS_INHOUSE_BY_NATIONALITY'
});