'use strict';

sntRover.constant('RVReportFiltersConst', {
	'DATE_RANGE': true,
	'CANCELATION_DATE_RANGE': true,
	'CANCELLATION_DATE_RANGE': true,
	'ARRIVAL_DATE_RANGE': true,
	'GROUP_START_DATE_RANGE': true,
	'DEPOSIT_DATE_RANGE': true,
	'CREATE_DATE_RANGE': true,
	'PAID_DATE_RANGE': true,
	'SINGLE_DATE': true,
	'ADJUSTMENT_DATE_RANGE': true,
	'TIME_RANGE': true,
	'CICO': true,
	'INCLUDE_COMPANYCARD_TA_GROUP': true,
	'GROUP_COMPANY_TA_CARD': true,
	'INCLUDE_GUARANTEE_TYPE': true,
	'INCLUDE_CHARGE_GROUP': true,
	'INCLUDE_CHARGE_CODE': true,
	'CHOOSE_MARKET': true,
	'CHOOSE_SEGMENT': true,
	'CHOOSE_SOURCE': true,
	'CHOOSE_BOOKING_ORIGIN': true,
	'HOLD_STATUS': true,
	'DAYS_0_30': true,
	'ACCOUNT_SEARCH': true,
	'GROUP_CODE': true
});