'use strict';

// KM is short for Key Mirror
sntRover.constant('RVReportFiltersKmConst', {
	'DATE_RANGE': 'DATE_RANGE',
	'CANCELATION_DATE_RANGE': 'CANCELATION_DATE_RANGE',
	'CANCELLATION_DATE_RANGE': 'CANCELLATION_DATE_RANGE',
	'ARRIVAL_DATE_RANGE': 'ARRIVAL_DATE_RANGE',
	'GROUP_START_DATE_RANGE': 'GROUP_START_DATE_RANGE',
	'DEPOSIT_DATE_RANGE': 'DEPOSIT_DATE_RANGE',
	'CREATE_DATE_RANGE': 'CREATE_DATE_RANGE',
	'PAID_DATE_RANGE': 'PAID_DATE_RANGE',
	'SINGLE_DATE': 'SINGLE_DATE',
	'ADJUSTMENT_DATE_RANGE': 'ADJUSTMENT_DATE_RANGE',
	'TIME_RANGE': 'TIME_RANGE',
	'CICO': 'CICO',
	'INCLUDE_COMPANYCARD_TA_GROUP': 'INCLUDE_COMPANYCARD_TA_GROUP',
	'GROUP_COMPANY_TA_CARD': 'GROUP_COMPANY_TA_CARD',
	'INCLUDE_GUARANTEE_TYPE': 'INCLUDE_GUARANTEE_TYPE',
	'INCLUDE_CHARGE_GROUP': 'INCLUDE_CHARGE_GROUP',
	'INCLUDE_CHARGE_CODE': 'INCLUDE_CHARGE_CODE',
	'CHOOSE_MARKET': 'CHOOSE_MARKET',
	'CHOOSE_SOURCE': 'CHOOSE_SOURCE',
	'CHOOSE_BOOKING_ORIGIN': 'CHOOSE_BOOKING_ORIGIN',
	'HOLD_STATUS': 'HOLD_STATUS',
	'GROUP_CODE': 'GROUP_CODE'
});